turingschool/backend-curriculum-site

module3/index.md
module3/pd_deliverables.md
module3/projects_overview.md
module3/success.md

WIP for mod 3 scope & sequence

mod 3 scope details

---

module3/projects/cloney_island.md

@sallymacnicholas @jmejia 
This PR adds the description of StackOverflow as a project for groups to clone during CloneyIsland. I can't think of a good fake name for this project. I've also done my best coming up with requirements for this project, but any and all feedback is much appreciated 👍

Add StackOverflow clone description

---

module3/projects/rails_engine.md
module3/slides/rales_engine_kickoff.md

* Add slides
* Update milestone and check-in sections

Update Rails Engine and add slides

---

module3/lessons/building_an_api.md
module3/slides/building_an_internal_api.md

* Add warmup to provide for discussion
* Remove Factory Girl review
* Update headers
* Add slides

Building an internal api

---

module3/lessons/intro_mod_three.markdown
module3/slides/m3_intro.md
module3/success.md

* Draft slides for M3 intro
* Minor adjustments to intro lesson
* Update PD section of success page

Update M3 success and add slides

---

module3/slides/intro_to_json.md

Create slides for intro to JSON lesson.

Add intro to JSON slides

---

module3/calendar.md
module3/lessons/advanced_active_record.md
module3/slides/advanced_activerecord.md

* Create lesson for Advanced AR
* Update calendar
* Remove empty lesson placeholder

Add Advanced AR Slides/Lesson

---

module3/slides/customizing_json.md

Add customizing json slides

---

module3/slides/advanced_activerecord.md

* Update warmup
* Add new methods

Update with 'find_by_sql' and 'select'

---

module4/lessons/javascript_without_a_browser.md

@case-eee 
- update to lesson plan
- ripped out modular information and one exercise at the bottom

update to javascript without a browser

---

module3/projects/apicurious.md

Update api curious

---

module3/lessons/archive/consuming_an_api.md
module3/lessons/consuming_an_api.md

* Update Consuming an API lesson to mirror VCR lesson so that VCR can be a continuation.
* Move MyChaimz to archive.
* Switch to RSpec.

Update m3 consuming api

---

module3/lessons/consuming_an_api.md
module3/lessons/using_figaro.md

* Create mini lesson for Figaro.
* Add warmup to Consuming an API lesson.

Add figaro mini-lesson

---

module3/lessons/testing_against_third_party_apis.md

VCR lesson now:
* Uses RSpec
* Removes material covered in consuming an API lesson from previous day.

Update VCR lesson

---

module3/index.md
module3/slides/decorators_and_presenters.md

Add lesson for decorators lesson. Includes info on presenters and other strategies.

Update poro lesson

---

module3/lessons/archive/understanding-multitenant-applications.md
module3/lessons/understanding-multitenant-applications.md

* Move existing multitenancy lesson to archive.
* Update multitenancy lesson to match slides.

Update multitenancy lesson

---

module3/index.md
module3/outlines/week1.md
module3/outlines/week2.md
module3/outlines/week3.md
module3/outlines/week4.md
module3/outlines/week5.md
module3/outlines/week6.md

* Add outlines consistent with M1.
* Add links from M3 index.

Add links to weekly outlines

---

module3/lessons/fundamental_rails_security.md
module3/slides/fundamental_rails_security.md

Add Fundamental Rails Security slides
* Create slides
* Create link to slides from lesson

Add fundamental rails security slides

---

module3/lessons/performance_dojo.markdown
module3/outlines/week5.md

Add Performance Dojo lesson from M4 folder in `turingschool/lessons`.

Add performance dojo lesson from old BE M4

---

module4/success.md

The big add is the Turing Stories Presentation. Be sure to read over it for clarity. I see now that I wrote it in the 2nd person, while the rest of the document is in 3rd person. Let me know if that seems unprofessional or causes too much cognitive dissonance. 
I also made a few other clarifications and changes to reflect the adjustments we've made throughout the module. They're also in the 2nd person.

Added Turing Stories and clarifications to B4 Success doc

---

module3/interview_prep/index.md

Minor change to address markdown formatting.

M3 interview prep

---

module3/interview_prep/index.md

Update link to mock interview activity

---

module3/assessment.md

Add assessment

---

module3/assessment.md

Update assessment layout

---

module1/slides/strings_and_integers.md
module1/slides/welcome_to_M1.md

Add slides for BEM1 1705 Day 1.

Add m1 slides

---

module4/success.md

Mostly changed the portfolio expectations to match our new calendar. Also updated some of the skills, but there wasn't much to change there.

Updated M4 success for 1611

---

module3/lessons/json_fundementals.md

- Introduce JSON as ruby instead of JS
- Put JS and JSON in the additional resources 
@jmejia made a few changes to this lesson

small changes to json lesson

---

module1/week_1.md

Adds links to BEM1 Week 1, Day 1 slides.

Update week 1 with slide links

---

module1/slides/primer_on_each.md

Update primer on each to reference HW instead of prework

---

module1/week_1.md

Add link to credit check slides

---

module1/slides/classes_instances_methods.md

Add slides for classes and instance methods

---

module1/lessons/debugging_redux.markdown
module1/slides/debugging.md
module1/week_2.md

Create slides and implement minor updates to the debugging lesson.

Update debugging lesson and add slides

---

module1/projects/b1_project_rubric_template.md
module1/success.md

Draft updated version of BEM1 `success` page.

Update BEM1 success page

---

module1/week_2.md

Updates Week 2.
Questions:
* Choose your own adventure?
* Git for Pairs?
* Thursday Projects?

Update week 2

---

module1/slides/beginner_enumerables.md
module1/week_2.md

Adds slides for beginner enum lesson.

Add enum slides

---

module4/lessons/whiteboard-prep.md

Whiteboard lesson for BEE4 students.

Add whiteboard lesson

---

module3/lessons/building_an_api.md

I'm using this lesson plan for a learning session at my work where I'll teach the team how to build an API. Thought I'd jump in and fix this minor error while I'm at it. =)

Add missing end-quote

---

module1/slides/testing_strategies_3.md
module1/week_4.md

Add slides and link to slides for week 4 testing lesson.

New testing lesson

---

module1/slides/testing_strategies_3.md
module1/week_3.md
module1/week_4.md

Move boolean logic activity from week 4 to week 3.

Move boolean

---

module1/slides/refactoring_patterns.md

Add slides for refactoring patterns

---

module1/slides/git_branching.md
module1/week_4.md

@mikedao Current thoughts on a Git with branches lesson. Let me know what you think!

Draft Git branching lesson

---

module1/lessons/object_relational_mapping.markdown

@s-espinosa @mikedao 
I took a crack at fleshing out the ORM lesson a bit after talking with Josh thinking through what I'd want to teach them about ORMs.  
It doesn't include a section covering your request Mike for "traversing verticals and passing self in order to do so."  I'll need to talk with you a bit more about that and then will go back and adjust the lesson from there.

Update Object Relational Mapping Lesson

---

module1/lessons/fixtures_mocks_stubs.md
module1/slides/fixtures_mocks_stubs.md

Add slides and make slight adjustments.

Add slides for mocks lesson

---

module4/success.md

@neight-allen thoughts on this?

Update PD deliverables

---

module4/index.md
module4/lessons/intro_to_professional_workflow.md

@case-eee @neight-allen ready for review!
Move link in index from week 4 to week 1

[WIP] Update Pivotal Tracker / workflow lesson

---

module1/weekly_outlines/week_1.md

Update based on new name of lesson.

Update M1 W1 link to variables strings and integers lesson

---

module1/weekly_outlines/week_1.md

Add core types, mythical creatures, and enums exercises.

Update week 1 homework

---

module1/lessons/intro_to_methods.md
module1/slides/intro_to_methods.md

* Create slides for intro to methods class.
* Add link to slides.

Add slides for intro to methods

---

module1/lessons/intro_to_classes.md
module1/slides/intro_to_classes.md

* Add slides for Intro to Classes lesson
* Create link to slides
* Fix code snippets in Intro to Classes lesson to include `to_s` when using `+` to concatenate

Create slides, add link to slides

---

module1/lessons/intro_to_classes.md
module1/slides/intro_to_classes.md

For Intro to Classes lesson:
* Change + concatenation to string interpolation
* Remove `.to_s` from variables that are now interpolated

Change + concatenation to interpolation

---

module1/lessons/intro_to_oop.md
module1/slides/intro_to_oop.md

* Add slides
* Add link
* Change concatenation to interpolation

Add intro to OOP slides

---

module1/lessons/intro_to_scope.md
module1/slides/intro_to_scope.md

Add intro to scope slides
Add link

Add intro to scope slides

---

module1/slides/intro_to_tdd.md

Add slides for intro to TDD lesson.

Add intro to TDD slides

---

module1/lessons/hashes_arts_and_crafts.md
module1/lessons/nested_collections.md

@s-espinosa 
Here is my split for the hash lessons.  The second lesson dives into nested hashing, it may be too much depending on how much is able to be covered during the first hash lesson.  I'm excited about the exposure though and an opportunity to follow up on hashes and nested data sets.

As split hash lesson

---

module4/lessons/sql-in-node.md
module4/lessons/testing-in-javascript.md

This is kind of rough at the moment. I need to polish up some sections, but this is the structure I'm planning on using. I also still need to write better READMEs for both apps so the students can actually get them up and running. The basic structure of the lesson:
1. Talk about unit tests vs integration tests
1. Download and setup java and repos
1. Walk through existing test and functionality
1. Code along a new test
1. Review AJAX
1. Get test to pass using AJAX
1. Students pair up and write another test and another functionality
And please ignore my small update to the other lesson. Bad PR.

Heavy rewrite of testing

---

module1/weekly_outlines/week_2.md

Change Night Writer to Enigma.

Update week 2 project

---

module1/lessons/inheritance.md
module1/slides/inheritance.md
module1/weekly_outlines/week_4.md

* Create inheritance lesson
* Create inheritance slides
* Add link to inheritance lesson from Week 4 outline

Add inheritance lesson

---

module1/lessons/testing_strategies_1.md
module1/weekly_outlines/week_3.md

@s-espinosa 
I combined a few parts of the existing testing lessons and rolled in some aspects of things they had questions about.  If it all looks good to you, it should be set to merge.

As testing strategies 1

---

module1/slides/git_branching.md
module1/weekly_outlines/week_3.md

* Move link to Git Branch lesson from Week 4 to Week 3 and update lesson.

Create git branch lesson

---

module1/lessons/intermediate_enumerables.md
module1/slides/intermediate_enumerables.md

Add slides for intermediate enumerables class.

Add intermediate enums

---

module1/weekly_outlines/week_4.md

Update BEM1 Week 4

---

module1/slides/class_methods.md

Add Class Methods slides

---

module1/lessons/archive/intro_to_modules.md
module1/lessons/intro_to_namespacing.md

As 1706 namespacing

---

module1/lessons/intro_to_namespacing.md
module1/slides/intro_to_namespacing.md
module1/weekly_outlines/week_5.md

* Add slides to namespacing lesson.
* Clean up whitespace in namespacing lesson.
* Update Week 5 outline.

Add namespacing

---

module4/lessons/contributing_to_open_source.markdown

@case-eee @neight-allen based on a conversation with a student, I think producing a new bug report is also valid. Let me know if I should add any detail, or if you disagree!

Add produce to the bug report options

---

changelog_proposals.md

Draft M1 changes

---

module2/homework/activerecord_and_database_practice.md

Changes examples back to match films as a continuation of the FilmFile work students complete in the afternoon.

Change homework back to FilmFile work

---

module2/homework/activerecord_and_database_practice.md
module2/index.md
module2/lessons/activerecord_associations.md
module2/slides/authorization/authorization.md
module2/weekly_outlines/week_1.md
module2/weekly_outlines/week_2.md
module2/weekly_outlines/week_3.md
module2/weekly_outlines/week_4.md
module2/weekly_outlines/week_5.md
module2/weekly_outlines/week_6.md

add week 1 for review

---

module4/projects/quantified-self/quantified-self.md

@tmikeschu @laurenfazah here are some minor updates to the QS markdown. some of them were typos, some minor organization, and some added additional detail for the project.
to do: create the Rails API starter repo (unless we feel like that's another thing they could do over intermission week?)

Minor updates to QS overview markdown

---

module4/projects/quantified-self/quantified-self-tracker-stories.csv

@laurenfazah @case-eee ready for review! I believe we decided on taking out the story from line 10? Let me know if I just made that up in my head.

Update tracker stories

---

module1/projects/credit_check.markdown
module1/projects/date_night.markdown
module1/projects/jungle_beat.markdown
module1/projects/learning_goals_by_project.md

Add Learning Goals to Date Night
Update Jungle Beat to include Learning Goal around iteration/recursion 
Update Learning Goal Tracking Doc

Update learning goals m1

---

module2/slides/intro_to_m2.md
module2/weekly_outlines/week_1.md

Add welcome slides for Module 2.

M2 welcome slides

---

module2/slides/intro_to_m2.md

Remove line since students already did it.

Remove note to move cubbies

---

module1/index.md
module1/lessons/refactoring_patterns_part_1.md
module1/weekly_outlines/week_1.md
module1/weekly_outlines/week_2.md
module1/weekly_outlines/week_3.md
module1/weekly_outlines/week_4.md
module1/weekly_outlines/week_5.md
module1/weekly_outlines/week_6.md

* Update projects (Night Writer instead of Enigma)
* Include PD links under Lessons
* Add homework sections to all weeks
* Make titles more consistent
* Add Week 6 Outline
* Leave out Bad Connection link
* Add Gear-up links

Update Weekly Outlines for 1708 v2

---

module1/conference_talks.md

Add markdown for weekly conference talk resources

Add conference talk resources

---

module1/lessons/intro_to_classes.md
module1/lessons/intro_to_methods.md
module1/lessons/intro_to_oop.md

@neight-allen @case-eee 
I added some language around Abstraction and Encapsulation to some M1 week 1 lessons. My aim here was to weave in a *very* brief introduction to these concepts while we are teaching other things.  
Is the information I've included correct? Do the places I've connected these concepts into our learning make sense?  
Thanks!

Update week 1

---

module1/lessons/intro_to_classes.md
module1/lessons/intro_to_methods.md
module1/lessons/intro_to_oop.md
module1/lessons/project_review.md

M1 project review

---

module2/lessons/crud_in_sinatra.md
module2/slides/crud_in_sinatra.md
module2/slides/how_the_web_works/slides.md

Add slides for CRUD in Sintra lesson.

Add CRUD in Sinatra slides

---

module1/lessons/debugging_with_pry.md
module1/slides/debugging_with_pry.md

* Augment learning goals
* Re-order enumerables to the beginning
* Add vocab, recap, and further learning sections 
* Add more context to debugging and pry repl
* Build out pry example wth an `each` block since the `each` section is now first.
@AliSchlereth & @neight-allen if you don't have a chance to merge this by 8ish, I'll do so myself. Thanks again for all the advice!

Final Lesson Plan for Debugging with Pry 1708

---

module1/lessons/intro_to_classes.md
module1/lessons/intro_to_methods.md

Move class intro section from intro to methods to intro to classes.

Move Class intro to intro_to_classes

---

module1/projects/perilous_journey.markdown
module1/projects/perilous_journey_iterations/extensions.md
module1/projects/perilous_journey_iterations/iteration_0.md
module1/projects/perilous_journey_iterations/iteration_1.md
module1/projects/perilous_journey_iterations/iteration_2.md
module1/projects/perilous_journey_iterations/iteration_3.md
module1/projects/perilous_journey_iterations/iteration_4.md
module1/projects/perilous_journey_iterations/iteration_5.md
module1/projects/perilous_journey_iterations/iteration_6.md
module1/slides/intro_to_oop.md
module1/weekly_outlines/week_1.md

Adds 6 iterations and extensions for the Perilous Journey B1 project

Perilous Journey iterations

---

module1/lessons/archive/how_testing_works_before_tdd.markdown
module1/lessons/how_testing_works.markdown
module1/lessons/intro_to_tdd.markdown
module1/lessons/testing_in_a_project.markdown

@AliSchlereth & @neight-allen could you give both the 'how testing works' & 'testing in a project a look'? I moved the breaking logic down into the testing in a project lesson for Wednesday because it seemed to fit better in my mind; let me know if you think it'd be better addressed tomorrow.

Update testing lessons

---

module2/index.md

Remove link to homework

---

module1/lessons/working_with_objects.md

@neight-allen @VictoriaVasys 
Here is a lesson I wrote for tomorrow's optional Object/Classes review session.

Add working with objects

---

module2/weekly_outlines/week_3.md

Update links to mix master to point to Rails 5 version.

Update links to mix master

---

module2/lessons/form_helpers_rails.markdown
module2/slides/forms_in_rails.md

Add slides for forms in Rails lesson.

Add forms in rails slides

---

module1/lessons/boolean_logic.markdown

@VictoriaVasys @neight-allen 
Here are some updated to the boolean lesson if you'd like to take a look.

As 1708 boolean logic

---

module2/lessons/active_record_on_models.md
module2/slides/active_record_on_models.md
module2/weekly_outlines/week_4.md

Add lesson to review using ActiveRecord from within a model.

Add ActiveRecord on Models lesson

---

module2/lessons/factory_girl.md
module2/lessons/how_the_web_works.md
module2/lessons/models_migrations_databases.md
module2/lessons/passing_data_with_sinatra.md
module2/slides/html_css_basics/html_css_basics.md
module2/weekly_outlines/week_1.md

@icorson3 Can you add the goals for your lessons to this branch?
My part of this PR is only long because we didn't have a How the Web Works lesson, just slides. Look at the other two for examples of what I did. Thanks!

Draft learning goals

---

module2/lessons/sessions_cookies_and_flashes.markdown

Add link to slides for sessions lesson.

Add link to slides

---

module1/lessons/class_methods.md

@neight-allen @VictoriaVasys 
Class Methods lesson plan ready for review!

Class methods

---

module2/lessons/intro_to_the_asset_pipeline.markdown
module2/slides/asset_pipeline_plus_heroku/asset_pipeline.md

* Update slides
* Adjust lesson and slides to conform to one another

Update asset pipeline class

---

module2/weekly_outlines/week_5.md

Minor updates to BEM2 Week 5 outline.

Update Week 5

---

changelog_proposals.md

@icorson3 Can you take a look at these to see if it's consistent with what we've been discussing? Is there anything in here you don't like? Anything we were thinking of that we need to add? Thanks!

Draft changes to M2 for 1710 inning

---

module4/success.md

@laurenfazah how's this look as far as the success page goes? did i miss anything?

B4 success updates

---

module2/lessons/intro_to_mvc.md
module2/lessons/restful_routes_and_crud.md
module2/slides/intro_to_mvc.md
module2/slides/restful_routes_and_crud.md

Add slides

---

module1/lessons/nested_collections.md

Add `ruby` to syntax highlight to see if that highlights the code correctly.

Add highlighting to nested collections

---

module1/homework/bad_connection.md

@VictoriaVasys @mikedao 
Added iterations. 1-3 there isn't much to the directions, did I miss anything? Does 4 make sense? Did I give to much information in the suggested output?

Add iterations

---

module1/lessons/intro_to_scope.md

1710 scope

---

module2/lessons/activerecord_associations.md
module2/slides/activerecord_associations.md

Associations Slides

---

module4/projects/quantified-self/quantified-self.md

@laurenfazah @kat3kasper thoughts on this updated rubric? a few bigger things here, i removed the planning section and i added a communication section. i also wasn't sure what to put in the testing section. i'm fine with what's here currently (expecting unit tests for their frontend code, but not putting a number on how many)

Update QS rubric

---

module2/lessons/feature_testing_in_sinatra.md
module2/slides/feature_testing_in_sinatra.md

Update feature testing lesson and slides.

Update feature testing lesson and slides

---

module2/lessons/activerecord_associations.md
module2/lessons/joins_group_order.md
module2/weekly_outlines/week_2.md

* Draft Joins, Group, Order lesson
* Update Week 2 outline
* Fix typo in Associations lesson

Create Joins, Group, Order lesson

---

module2/weekly_outlines/week_6.md

Add non-violent feedback video to week six opposite LittleShop evals.

Add non-violent communication video to week 6

---

module2/lessons/models_migrations_databases.md

Changes Authors/Books/Genres to Directors/Movies/Actors.

Update models migrations and databases

---

module1/lessons/working_with_files.markdown

Change order of working_with_files lesson

Add further commands to working with files

---

module4/capstone_project_overview.md

@laurenfazah & @kat3kasper here's my first pass at updating the capstone project rubric. any feedback is much appreciated 😸

Update Capstone rubric

---

module2/lessons/namespacing.md
module2/lessons/sessions_cookies_and_flashes.markdown
module2/weekly_outlines/week_3.md

* Create sessions exercise
* Update namespacing lesson (remove nested resources since that was handled in an earlier lesson)
* Add link to Auth exploration gist

Add sessions and namespacing exercises

---

module1/projects/enigma.markdown
module1/projects/event_reporter.md

* Based on the project found here: https://github.com/turingschool/curriculum/raw/master/source/projects/event_reporter.markdown
@AliSchlereth @mikedao Here's the updated markdown; I just added the rubric (with an additional version control portion, & changed method-length expectations to 7-lines  & expected enums to be best-choice) and fixed the link for the API in extensions.
I haven't had a chance to look it over carefully, but will do so later tonight. Let me know if anything stands out to you.

Create Event Reporter project

---

module2/projects/mini-project.markdown

Add requirements to M2 mini-project for original project to be approved.

Add requirements for an original project

---

module2/lessons/authorization.md
module2/slides/authorization/authorization.md
module2/weekly_outlines/week_4.md

Update to:
* include slides
* move gist questions to checks for understanding
* reference movie mania instead of existing auth repo
* name of file to match name in calendar

Update authorization lesson

---

module2/slides/authorization/authorization.md

Remove layout from slides since these are being used by Deckset.

Remove layout

---

module2/projects/mini-project.markdown

@s-espinosa took my first pass at the checklist! if you like it, merge it

add checklist

---

module2/lessons/accessibility_best_practices.markdown

* Remove some formatting.
* Remove leading white space on bulleted and numbered lists.

Reformat accessibility lesson so that it doesn't make page wider

---

module2/lessons/accessibility_best_practices.markdown
module2/slides/accessibility_best_practices.md
module2/weekly_outlines/week_5.md

* Add slides
* Update lesson to match slides
* Update weekly outline

Add accessibility slides

---

module2/weekly_outlines/week_5.md

Add link to CSV Violations challenge

---

module1/lessons/intro_to_variables_and_data_types.markdown
module1/lessons/working_with_git.markdown

Update B1 working with git lesson

---

module1/slides/introducing_hashes.md

Add question about previous knowledge

---

module1/weekly_outlines/week_1.md

Fix link typo

---

module2/lessons/joins_group_order.md

@icorson3 
Here are some updates to tomorrow's joins group order class. 
* Add more SQL queries
* Change module_id to course_id and persist to use Course everywhere
* Add Sinatra app to use for demonstrating

1710 joins group order

---

module1/lessons/debugging_techniques.md
module1/slides/debugging_techniques.md

Add debugging slides

---

module1/lessons/git_for_pairs.md

* Remove trailing whitespace
* Remove `git add .`
* Add `git add -p`
* Remove `hub`

Update Git for Pairs

---

module2/lessons/form_helpers_rails.markdown

@AliSchlereth made some updates to mondays lesson. let me know if you have other suggestions.

update form lesson

---

module2/lessons/rest_routing_and_controllers_in_rails.markdown

@AliSchlereth made updates to the lesson to provide a total narrative for the code along. Let me know if you have suggestions!

update code along for rails new day

---

module2/misc/blogger.md

@AliSchlereth if you have any suggestions, let me know

Blogger update

---

module2/lessons/models_migrations_databases.md

Update models_migrations_databases lesson
* Add testing
* Add vocab section
* Update warm up and recap questions 
@icorson3

Add testing to models_migrations_databases

---

module2/misc/blogger.md

Drying up the tutorial a bit. Refactoring with set_article could be included on the show method as well.

Blogger: Add show to before_action :set_article

---

module1/lessons/intro_to_scope.md
module1/lessons/number_systems.markdown
module1/weekly_outlines/week_3.md

* Add links to W3 weekly outline
* Remove whitespace from lessons

Add week 3 lessons

---

module1/lessons/git_for_pairs.md
module1/slides/git_for_pairs.md

Add slides for git for pairs

---

module2/slides/nested_resources.md

@AliSchlereth added TDD to nested resource lesson...not sure if I will have enough time but lets do it!

update nested resource lesson with TDD

---

module2/lessons/route_helpers.md

@icorson3 
Add structure to group sharing and practice sections. 
Add Vocab section
Update WarmUp & WrapUp questions to align with learning goals

Update route helper lesson

---

module2/lessons/factory_bot.md

@icorson3 
Made some further tweaks to the FactoryBot lesson. Let me know if you see any changes I should make.

1710 factory girl

---

module1/lessons/number_systems.markdown
module1/slides/number_systems.md

Add number systems slides

---

module2/lessons/authentication.md

@icorson3 
Updates to the authentication lesson.
-Add some more explicit error messages
-Add vocab, learning goals, and wrap up questions
-Update warm up questions
-Adjust formatting a little bit
-Add links to docs for gems and methods we use

1710 authorization

---

module2/misc/blogger.md

In Blogger.md the link to contribute suggestions, fixes and such was 404.
Link is now correct.

Blogger.md - Fix link to contribute to tutorial on GitHub

---

module2/misc/blogger.md

The tutorial doesn't create a file/path for articles_helpers.rb and the code snippet it refers to is in articles_controller.rb

Fix file path on example

---

module1/lessons/boolean_logic.markdown
module1/slides/boolean_logic.md

Add boolean logic slides

---

module2/success/review_questions_part_1.md

@icorson3 
Review questions for wk1-2

Add initial review questions

---

module2/lessons/accessibility_best_practices.markdown

update accessibilty lesson

---

module2/misc/cart_exploration.md
module2/weekly_outlines/week_4.md

@AliSchlereth added an actual markdown for cart exploration with a good resource and an activity. Let me know if you think there is something else we shoud add.

add better resource and attempt on their own

---

module2/lessons/asset_pipeline.md
module2/slides/asset_pipeline/asset_pipeline.md

* Update lesson
* Update slides

Update Asset Pipeline lesson and slides

---

module2/lessons/asset_pipeline.md
module2/slides/asset_pipeline/asset_pipeline.md

Add challenge to Asset Pipeline lesson.

Add challenge

---

module2/lessons/cart_implementation.markdown

@AliSchlereth some updates to make it cleaner mostly!

Cart order update

---

module2/misc/blogger.md

@icorson3 
Here is Blogger updated with Testing. I also linked my repo which I built out along the way as an extra resources since the later iterations have less explicit directions.  
There are probably plenty of typos in what I added. If you have time let me know what you think. If not our students can hunt out the typos.

Add testing to blogger

---

module4/projects/quantified-self/quantified-self.md

* Update link to submission repo.

Update submission repo link

---

module2/lessons/passing_data_with_sinatra.md

@icorson3 
*Add vocab, warm up, and wrap up sections
*Add section for query parameters
*Reorder to put local variables section on its own
*Update minor wording on exercises section to use more restful routes

Update passing data with Sinatra

---

module4/lessons/webpack-demystified.md
module4/slides/webpack.md

Update webpack lesson

---

module4/lessons/webpack-demystified.md
module4/slides/webpack.md

* Fix directory name in slides.
* Add info on why we use `npm run build`.

Webpack fixes

---

module2/misc/blogger.md

Add section to check schema.
Add active designer gem and description of pry.

Add schema and active designer

---

module4/lessons/archive/intro_to_express.md
module4/lessons/archive/sql-in-node.md
module4/lessons/intro_to_express.md
module4/slides/intro_to_express.md
module4/slides/sql_in_node.md

* Move SQL and Express lessons to archives.
* Update SQL and Express lessons.
* Create slides for SQL and Express lessons.

Update express lesson

---

module4/lessons/organize-an-express-app.md
module4/slides/organizing_an_express_app.md

* Update organizing an Express app lesson.
* Create slides for organizing an Express app lesson.

Update lesson on organizing an Express app

---

module2/lessons/design_principles.md

add design class

---

module4/lessons/fe_dev_tool_debugging.md

- Removed ajax in lesson text
- Switched example from an ajax to a fetch call

Update ajax to fetch calls

---

module4/index.md
module4/lessons/fe_dev_tool_debugging.md
module4/lessons/unit_testing_express_server.md

Create server testing lp

---

module2/lessons/diagramming_request_response_cycle.md
module2/weekly_outlines/week_3.md

@icorson3 Here is the markdown for the Diagramming the Web class tomorrow. Let me know if you see any adjustments.

Diagramming the web

---

module1/lessons/ruby_project_etiquette.md
module1/lessons/ruby_project_etiquette_part2.md

@mikedao 
Alterations to both Ruby Project Etiquette lessons.

As ruby proj ettiquette

---

module4/index.md

Update link to web security lesson

---

module3/lessons/jquery_and_dom.md

- updated some code pens
- cut out advanced selector bit
- added CFUs

Update jQuery lesson

---

module2/lessons/sql_refresher.md

@AliSchlereth @s-espinosa updated SQL refresh to be with little shop, any other suggestions? Might need a few more queries...

update sql refresh

---

module2/projects/bike-share-redux.md

@AliSchlereth @s-espinosa my branch for redux

add bik share redux

---

module2/weekly_outlines/week_4.md

add bike share

---

module4/index.md
module4/projects/open_source_project.md

- some details on spec
- in index.md

Update B4 Open Source 

---

module4/lessons/fetch_refresher.md

Fetch refresher update

---

module3/lessons/building_an_api.md
module3/slides/building_an_internal_api.md

Small updates to lesson and slides.

Update building an API lesson

---

module3/lessons/building_an_api.md
module3/slides/m3_intro.md

* Change `require` to `require_relative` for FactoryBot in Building an API lesson.
* Update M3 projects in intro slides.

Change require to require_relative

---

module3/lessons/customizing_json_in_your_api.md
module3/slides/customizing_json.md

* Update Customizing JSON lesson
* Update related slides

Update lesson and slides

---

module2/projects/bike-share-redux.md
module2/projects/mini-project.markdown

@iandouglas 
Updating rubrics to use categories for each project. 
Updated wording to set expectations for students around when/how they will get or should see feedback.
Let me know if you see anything you think should be changed.

Update b2 rubrics 1801

---

module3/lessons/customizing_json_in_your_api.md

* Remove price from show/index
This is not an attribute on the item model.

Remove price from item show/index

---

module3/lessons/getting_started_with_oauth.md
module3/slides/getting_started_with_oauth.md

Update oauth lesson

---

module3/slides/getting_started_with_oauth.md

* Update OAuth slides to include Faraday.

Update OAuth slides

---

module1/projects/black_thursday.markdown
module1/projects/black_thursday_iterations/iteration_0.markdown
module1/projects/black_thursday_iterations/iteration_1.markdown
module1/projects/black_thursday_iterations/iteration_2.markdown
module1/projects/black_thursday_iterations/iteration_3.markdown
module1/projects/black_thursday_iterations/iteration_4.markdown
module1/projects/black_thursday_iterations/iteration_5.markdown

This PR removes all relationship layer requirements, i.e. this functionality is no longer required:
```ruby
item = Item.new
item.merchant
```
Relationships between objects are implicitly required by the analysis layer.
Also adds the create, update, and delete CRUD operations for each repository.

Update black thursday

---

prework/index.html

Added:
* link to learn fundamental typing
* blog that has an explanation for some git commands
* optional tools that may be helpful to install (Evernote, Spectacle, CopyClip, Howler Timer)

Add resources to prework. 

---

prework/index.html

This gist/markdown explanation taken directly from the Front End program's pre-work, under Day 1.

Add gist and MD explanation to Day 1

---

module1/projects/battleship.markdown
module1/projects/http_tutorial.md

This PR makes playing through a web browser the only extension for the Battleship project. It also adds a tutorial on HTTP, and links that tutorial in the extension.

Battleship extensions

---

module2/projects/bike-share-reduced.md

Removed the weather conditions portion of the project to account for a shortened module (1803 module, for example, had the Memorial Day weekend), or for smaller teams.

reduced Bike Share project

---

module1/lessons/testing_strategies_1.md
module1/slides/testing_strategies_4.md

* Create slides for testing lesson
* Add link to new slides

Create new slides and add link

---

module1/projects/night_writer.markdown

@BrianZanti @memcmahon 
Here are my thoughts for an updated Night Writer spec.
* Break into iterations matching rubric scores.
* Break down steps for each iteration.
* Made requirement for braille file width consistent with examples.
* Move capitals to Iteration 4.
* Capitalize Braille throughout.

Update Night Writer spec

---

_includes/navigation.html
prework/archive/1804/index.html
prework/archive/pre_0718_index.html
prework/index.md

@BrianZanti @s-espinosa - This updates the curriculum site with a prework index geared toward the pre-work repository that we have been working on.  Let me know your thoughts!

Updates Prework - External Lessons with Skeleton Repo

---

module1/lessons/archive/methods_and_return_values.md
module1/lessons/methods_and_return_values.md

Updates with Credit Check example.

Methods Arguments and Return Values

---

module2/lessons/intermediate_active_record.md

- Parties renamed to Party to reflect model name
- Candidate belongs to party, not has many parties
- Fixed method name discrepancy between question and code sample in the exercise section

Documentation syntax fixes to reflect database schema 

---

module1/lessons/how_testing_works.markdown

Reverts turingschool/backend-curriculum-site#551
Reason - We are no longer using the Credit Check example, reverting to previous status of this class.

Revert "how testing works"

---

module1/projects/sorting_cards/iteration_1.md

Updates Sorting Cards project to have consistent Guess class iVars

Updates Guess iVars

---

module4/slides/organizing_an_express_app.md

Change names of models and controllers in slides

---

module1/lessons/inheritance.md

Adds `initialize` method to Employee superclass to match exercise parameters.

Update super exercise

---

module1/exercises/index.md
module1/independent_challenges/index.md
module1/index.md

This page has a description of the independent challenges overall, a description of the difficulty involved in each week, and an example for each week.

Adds page for independents

---

module1/lessons/objects_classes_instances.md

* Adds a section with class interaction
* Extends warmup
* Changes argument names so as not to confuse them with instance variables

Updates Objects, Instances, Classes

---

module1/projects/battleship/iteration_1.md
module1/projects/battleship/iteration_2.md
module1/projects/battleship/iteration_3.md
module1/projects/battleship/iteration_4.md
module1/projects/battleship/overview.md
module1/projects/battleship/requirements.md
module1/projects/battleship/rubric.md
module1/projects/battleship/setup.md
module1/projects/battleship/submission.md
module1/projects/cross_check/iterations/command_line.md
module1/projects/cross_check/iterations/file_io.md
module1/projects/cross_check/iterations/game_statistics.md
module1/projects/cross_check/iterations/league_and_season_statistics.md
module1/projects/cross_check/iterations/team_statistics.md
module1/projects/cross_check/iterations/website.md
module1/projects/cross_check/rubric.md
module1/projects/enigma/encryption.md
module1/projects/enigma/requirements.md
module1/projects/enigma/rubric.md
module1/projects/enigma/setup.md
module1/projects/enigma/submission.md
module1/projects/flashcards/iteration_1.md
module1/projects/flashcards/iteration_2.md
module1/projects/flashcards/iteration_3.md
module1/projects/flashcards/iteration_4.md
module1/projects/flashcards/peer_code_review.md
module1/projects/flashcards/requirements.md
module1/projects/flashcards/rubric.md
module1/projects/flashcards/setup.md
module1/projects/flashcards/submission.md

Adds links to project home pages.

Project links

---

module2/misc/blogger_iteration_0.md

Model Tests
Before we dive into the deep and start changing things, let's ("great") a test to help drive our development and keep ("up") focused. Within spec/models touch article_spec.rb
I think that should be...
Model Tests
Before we dive into the deep and start changing things, let's create a test to help drive our development and keep us focused. Within spec/models touch article_spec.rb
closes #524

Fix two typo errors in iteration_0

---

module1/projects/cross_check/index.md
module1/projects/cross_check/iterations/game_statistics.md
module1/projects/cross_check/iterations/season_statistics.md
module1/projects/cross_check/iterations/team_statistics.md

@ameseee Cross Check updates. Let me know if you have any comments!

Update spec based on student feedback

---

module2/misc/blogger_iteration_0.md

Corrected typo in feature test from .new to .create!

Update blogger_iteration_0.md typo in feature test from .new to .create!

---

module1/projects/jungle_beat.markdown

I noticed that periods were missing in three places where it would be consistent with the overall style to do so, and added them.

Add periods to make style consistent

---

module1/projects/battleship/iteration_3.md

Correcting small typo on Iteration 3 page of Battleship project for Mod 1 BE.

Correct show to shown

---

module1/projects/futbol/index.md

Two small typo corrections to overall description of "Futbol" project.

Remove extraneous article and extra space

---

module1/projects/index.md
module1/projects/war_or_peace/index.md
module1/projects/war_or_peace/iteration1.md
module1/projects/war_or_peace/iteration2.md
module1/projects/war_or_peace/iteration3.md
module1/projects/war_or_peace/iteration4.md
module1/projects/war_or_peace/requirements.md
module1/projects/war_or_peace/rubric.md
module1/projects/war_or_peace/setup.md

Adds alternate week 1 independent project for BEM1

War or peace

---

module1/lessons/mocks_stubs.md

Focuses more on the syntax and real life examples from the perspective of test refactoring; rather than starting from scratch

Update Mocks and Stubs

---

module3/lessons/intro_to_background_workers.md

Unless someone have secret access to Ruby 4 :)
[in that case, do we have types??]

Minor typo.
